server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: _
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: org.hibernate.dialect.PostgreSQLDialect
